spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nagadb2.cbvgdaawkqbe.us-east-1.rds.amazonaws.com/nagadb2?useSSL=false
    username: root2
    password: ssrpknt2
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
